-- AUTO-GENERATED by tools/crawl_wowhead_classic.py
local ADDON_NAME = ...
local DQTC = _G[ADDON_NAME]
DQTC.DataSources = DQTC.DataSources or {}
DQTC.DataSources.wowhead = {
  quests = {},
  npcs = {},
  objects = {},
  itemDrops = {},
  itemObjectDrops = {},
  itemNames = {},
  areaToUiMap = {},
}
