-- AUTO-GENERATED by tools/crawl_wowhead_classic.py. Do not edit by hand.
local ADDON_NAME = ...
local DQTC = _G[ADDON_NAME]
DQTC.DataSources = DQTC.DataSources or {}
DQTC.DataSources.wowhead = DQTC.DataSources.wowhead or {}
DQTC.DataSources.wowhead.itemNames = {
  [752] = "Red Burlap Bandana",
  [782] = "Painted Gnoll Armband",
  [829] = "Red Leather Bandana",
  [1931] = "Huge Gnoll Claw",
  [3110] = "Tunnel Rat Ear",
  [3172] = "Boar Intestines",
  [3173] = "Bear Meat",
  [3174] = "Spider Ichor",
}
