-- AUTO-GENERATED by tools/crawl_wowhead_classic.py. Do not edit by hand.
local ADDON_NAME = ...
local DQTC = _G[ADDON_NAME]
DQTC.DataSources = DQTC.DataSources or {}
DQTC.DataSources.wowhead = DQTC.DataSources.wowhead or {}
DQTC.DataSources.wowhead.itemDrops = DQTC.DataSources.wowhead.itemDrops or {}
DQTC.DataSources.wowhead.itemObjectDrops = DQTC.DataSources.wowhead.itemObjectDrops or {}
DQTC.DataSources.wowhead.itemDrops[752]={38}
DQTC.DataSources.wowhead.itemDrops[782]={97,478}
DQTC.DataSources.wowhead.itemDrops[829]={95,121,122,449,450,481,502,504,589,590,834,6180}
DQTC.DataSources.wowhead.itemDrops[1931]={448}
DQTC.DataSources.wowhead.itemDrops[3110]={1172,1173,1174,1175,1176,1177}
DQTC.DataSources.wowhead.itemDrops[3172]={157,345,454,547,1190,1191,1192,4422,4511,4512,4514,7333,7334}
DQTC.DataSources.wowhead.itemDrops[3173]={1130,1186,1188,1189,1225,1778,1797,1961,2163,2164,2165,6788,12432}
DQTC.DataSources.wowhead.itemDrops[3174]={217,442,471,505,539,569,574,616,930,949,1111,1112,1184,1185,1195,1780,1781,3819,3820,3821,4005,4006,4007,4040,4263,4264,11921,12433,14266,221169}
