-- AUTO-GENERATED by tools/crawl_wowhead_classic.py. Do not edit by hand.
local ADDON_NAME = ...
local DQTC = _G[ADDON_NAME]
DQTC.DataSources = DQTC.DataSources or {}
DQTC.DataSources.wowhead = DQTC.DataSources.wowhead or {}
DQTC.DataSources.wowhead.quests = DQTC.DataSources.wowhead.quests or {}
DQTC.DataSources.wowhead.quests[11]={n="Riverpaw Gnoll Bounty",l=10,rl=6,f=1,s={963},e={963},o={{t="item",i=782}},r=77,pq={239}}
DQTC.DataSources.wowhead.quests[18]={n="Brotherhood of Thieves",l=4,rl=2,f=1,s={823},e={823},o={{t="item",i=752}},r=77,pq={783}}
DQTC.DataSources.wowhead.quests[153]={n="Red Leather Bandanas",l=15,rl=10,f=1,s={878},e={878},o={{t="item",i=829}},r=77}
DQTC.DataSources.wowhead.quests[176]={n="Wanted:  'Hogger'",l=11,rl=5,f=1,s={},e={240},o={{t="item",i=1931}},r=77}
DQTC.DataSources.wowhead.quests[239]={n="Westbrook Garrison Needs Help!",l=10,rl=6,f=1,s={240},e={963},o={},r=77,pq={76},nq=11}
DQTC.DataSources.wowhead.quests[353]={n="Stormpike's Delivery",l=15,rl=9,f=1,s={1416},e={1343},o={},r=77,pq={1097}}
DQTC.DataSources.wowhead.quests[416]={n="Rat Catching",l=11,rl=10,f=1,s={1340},e={1340},o={{t="item",i=3110}},r=77}
DQTC.DataSources.wowhead.quests[418]={n="Thelsamar Blood Sausages",l=11,rl=7,f=1,s={1963},e={1963},o={{t="item",i=3172},{t="item",i=3173},{t="item",i=3174}},r=77}
DQTC.DataSources.wowhead.quests[1097]={n="Elmore's Task",l=15,rl=9,f=1,s={514},e={1416},o={},r=77,nq=353}
DQTC.DataSources.wowhead.quests[1338]={n="Stormpike's Order",l=14,rl=9,f=1,s={1343},e={5413},o={},r=77}
DQTC.DataSources.wowhead.quests[1339]={n="Mountaineer Stormpike's Task",l=15,rl=9,f=1,s={1340},e={1343},o={},r=77,nq=1338}
