#!/usr/bin/env python3
"""
Build Database/Classic/EventQuests.lua from Questie holiday quest lists.

Usage:
  python tools/convert_event_quests.py
"""

from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
QUESTIE_HOLIDAYS = ROOT.parent / "Questie" / "Database" / "Corrections" / "Holidays" / "quests"
OUT = ROOT / "Database" / "Classic" / "EventQuests.lua"

# tinsert(eventQuests, {"Winter Veil", 8827, "25/12", "2/1"})
# tinsert(eventQuests, {"Winter Veil", 7063})
# tinsert(eventQuests, {"Winter Veil", 7043, nil, nil, nil, nil, Questie.IsSoD})
PATTERN = re.compile(
    r'tinsert\(\s*eventQuests\s*,\s*\{\s*"([^"]+)"\s*,\s*(\d+)'
    r'(?:\s*,\s*([^,}]+))?'  # [3] start date or nil
    r'(?:\s*,\s*([^,}]+))?'  # [4] end date or nil
    r'(?:\s*,\s*([^,}]+))?'  # [5] start HH:MM
    r'(?:\s*,\s*([^,}]+))?'  # [6] end HH:MM
    r'(?:\s*,\s*([^,}]+))?'  # [7] hide flag
    r'\s*\}\s*\)',
    re.M,
)


def clean_str(tok: str | None) -> str | None:
    if tok is None:
        return None
    tok = tok.strip()
    if tok in ("nil", ""):
        return None
    if tok.startswith('"') and tok.endswith('"'):
        return tok[1:-1]
    return None


def should_skip_hide(hide_tok: str | None) -> bool:
    """Skip only when Questie would hide on Classic Era."""
    if hide_tok is None:
        return False
    tok = hide_tok.strip()
    if tok == "true":
        return True
    # Questie.IsSoD / expansion checks are false on Era → do not hide
    return False


def main() -> None:
    if not QUESTIE_HOLIDAYS.exists():
        raise SystemExit(f"Questie holidays not found: {QUESTIE_HOLIDAYS}")

    entries: dict[int, dict] = {}
    for path in sorted(QUESTIE_HOLIDAYS.glob("*.lua")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in PATTERN.finditer(text):
            event, qid_s, sd, ed, sh, eh, hide = m.groups()
            qid = int(qid_s)
            if should_skip_hide(hide):
                continue
            info = {"e": event}
            sd_v = clean_str(sd)
            ed_v = clean_str(ed)
            sh_v = clean_str(sh)
            eh_v = clean_str(eh)
            if sd_v and ed_v:
                info["sd"] = sd_v
                info["ed"] = ed_v
            if sh_v and eh_v:
                info["sh"] = sh_v
                info["eh"] = eh_v
            # Later files can overwrite; last write wins (fine for duplicates)
            entries[qid] = info

    lines = [
        "-- AUTO-GENERATED by tools/convert_event_quests.py from Questie holiday lists.",
        "-- Holiday quests are hidden unless their event (and optional date window) is active.",
        "local ADDON_NAME = ...",
        "local DQTC = _G[ADDON_NAME]",
        "DQTC.Data = DQTC.Data or {}",
        "DQTC.Data.eventQuests = {",
    ]
    for qid in sorted(entries):
        info = entries[qid]
        parts = [f'e="{info["e"]}"']
        if "sd" in info:
            parts.append(f'sd="{info["sd"]}"')
            parts.append(f'ed="{info["ed"]}"')
        if "sh" in info:
            parts.append(f'sh="{info["sh"]}"')
            parts.append(f'eh="{info["eh"]}"')
        lines.append(f"  [{qid}]={{{','.join(parts)}}},")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(entries)} event quests)")


if __name__ == "__main__":
    main()
